<?php

declare(strict_types=1);

namespace Whsv26\Functional\Collection;

use Whsv26\Functional\Core\Option;
use Whsv26\Functional\Collection\Immutable\Map\Entry;

/**
 * @template TKey
 * @template-covariant TValue
 * @psalm-immutable
 */
interface MapChainableOps
{
    /**
     * Produces new collection with given element
     *
     * ```php
     * >>> HashMap::collectPairs([['a', 1], ['b', 2]])->updated('b', 3)->toArray();
     * => [['a', 1], ['b', 3]]
     * ```
     *
     * @template TKeyIn
     * @template TValueIn
     * @param TKeyIn $key
     * @param TValueIn $value
     * @return Map<TKey|TKeyIn, TValue|TValueIn>
     */
    public function updated(mixed $key, mixed $value): Map;

    /**
     * Produces new collection without an element with given key
     *
     * ```php
     * >>> HashMap::collectPairs([['a', 1], ['b', 2]])->removed('b')->toArray();
     * => [['a', 1]]
     * ```
     *
     * @param TKey $key
     * @return Map<TKey, TValue>
     */
    public function removed(mixed $key): Map;

    /**
     * Filter collection by condition
     *
     * ```php
     * >>> HashMap::collectPairs([['a', 1], ['b', 2]])->filter(fn(Entry $e) => $e->value > 1)->toArray();
     * => [['b', 2]]
     * ```
     *
     * @psalm-param callable(Entry<TKey, TValue>): bool $predicate
     * @psalm-return Map<TKey, TValue>
     */
    public function filter(callable $predicate): Map;

    /**
     * A combined {@see MapOps::map} and {@see MapOps::filter}.
     *
     * Filtering is handled via Option instead of Boolean.
     * So the output type TValueOut can be different from the input type TValue.
     *
     * ```php
     * >>> HashMap::collectPairs([['a', 'zero'], ['b', '1'], ['c', '2']])
     * >>>     ->filterMap(fn(Entry $e) => is_numeric($e) ? Option::some((int) $e) : Option::none())
     * >>>     ->toArray();
     * => [['b', 1], ['c', 2]]
     * ```
     *
     * @psalm-template TValueOut
     * @psalm-param callable(Entry<TKey, TValue>): Option<TValueOut> $callback
     * @psalm-return Map<TKey, TValueOut>
     */
    public function filterMap(callable $callback): Map;

    /**
     * Map collection and flatten the result
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['2', 2], ['5', 5]]);
     * => HashMap('2' -> 2, '5' -> 5)
     *
     * >>> $collection
     * >>>     ->flatMap(fn(Entry $e) => [
     * >>>         [$e->value - 1, $e->value - 1],
     * >>>         [$e->value, $e->value],
     * >>>         [$e->value + 1, $e->value + 1]
     * >>>     ])
     * >>>     ->toArray();
     * => [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6]]
     * ```
     *
     * @experimental
     * @psalm-template TKeyOut
     * @psalm-template TValueOut
     * @psalm-param callable(Entry<TKey, TValue>): iterable<array{TKeyOut, TValueOut}> $callback
     * @psalm-return Map<TKeyOut, TValueOut>
     */
    public function flatMap(callable $callback): Map;

    /**
     * Alias for {@see MapOps::mapValues()}
     *
     * Produces a new collection of elements by mapping each element in collection
     * through a transformation function (callback)
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['1', 1], ['2', 2]]);
     * => HashMap('1' -> 1, '2' -> 2)
     *
     * >>> $collection->map(fn(Entry $e) => $e->value + 1);
     * => HashMap('1' -> 2, '2' -> 3)
     * ```
     *
     * @template TValueOut
     * @psalm-param callable(Entry<TKey, TValue>): TValueOut $callback
     * @psalm-return Map<TKey, TValueOut>
     */
    public function map(callable $callback): Map;

    /**
     * Produces a new collection of elements by mapping each element in collection
     * through a transformation function (callback)
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['1', 1], ['2', 2]]);
     * => HashMap('1' -> 1, '2' -> 2)
     *
     * >>> $collection->mapValues(fn(Entry $e) => $e->value + 1);
     * => HashMap('1' -> 2, '2' -> 3)
     * ```
     *
     * @template TValueOut
     * @psalm-param callable(Entry<TKey, TValue>): TValueOut $callback
     * @psalm-return Map<TKey, TValueOut>
     */
    public function mapValues(callable $callback): Map;

    /**
     * Produces a new collection of elements by assigning the values to keys generated by a transformation function (callback).
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['1', 1], ['2', 2]]);
     * => HashMap('1' -> 1, '2' -> 2)
     *
     * >>> $collection->mapKeys(fn(Entry $e) => $e->value + 1);
     * => HashMap(2 -> 1, 3 -> 2)
     * ```
     *
     * @template TKeyOut
     * @psalm-param callable(Entry<TKey, TValue>): TKeyOut $callback
     * @psalm-return Map<TKeyOut, TValue>
     */
    public function mapKeys(callable $callback): Map;

    /**
     * Returns sequence of collection keys
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['1', 1], ['2', 2]]);
     * => HashMap('1' -> 1, '2' -> 2)
     *
     * >>> $collection->keys(fn($elem) => $elem + 1)->toArray();
     * => ['1', '2']
     * ```
     *
     * @psalm-return Seq<TKey>
     */
    public function keys(): Seq;

    /**
     * Returns sequence of collection values
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['1', 1], ['2', 2]]);
     * => HashMap('1' -> 1, '2' -> 2)
     *
     * >>> $collection->values(fn($elem) => $elem + 1)->toArray();
     * => [1, 2]
     * ```
     *
     * @psalm-return Seq<TValue>
     */
    public function values(): Seq;
}
